# Generated by Django 5.0.2 on 2024-02-07 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15, unique=True)),
                ('student_passcode', models.CharField(default='ccz_new_student', max_length=30)),
                ('student_name', models.CharField(max_length=50, unique=True)),
                ('student_gender', models.CharField(default='', max_length=20)),
                ('student_contact', models.CharField(default='', max_length=20)),
                ('student_age', models.IntegerField(default=0)),
                ('student_address', models.CharField(default='', max_length=50)),
                ('student_email', models.EmailField(default='', max_length=50)),
                ('student_semester', models.CharField(default='', max_length=20)),
                ('student_lrn', models.CharField(default='', max_length=20)),
                ('student_placeofbirth', models.CharField(default='', max_length=50)),
                ('student_dateofbirth', models.CharField(default='', max_length=20)),
                ('student_civilstatus', models.CharField(default='', max_length=15)),
                ('student_citizenship', models.CharField(default='', max_length=20)),
                ('student_ethnicity', models.CharField(default='', max_length=20)),
                ('student_height', models.FloatField(default=0.0)),
                ('student_weight', models.FloatField(default=0.0)),
                ('student_religion', models.CharField(default='', max_length=20)),
                ('student_hsgrad', models.CharField(default='', max_length=50)),
                ('student_hsyear', models.IntegerField(default=0)),
                ('student_elemgrad', models.CharField(default='', max_length=50)),
                ('student_elemyear', models.IntegerField(default=0)),
                ('student_mothername', models.CharField(default='', max_length=50)),
                ('student_motheredu', models.CharField(default='', max_length=50)),
                ('student_motherattainment', models.CharField(default='', max_length=50)),
                ('student_fathername', models.CharField(default='', max_length=50)),
                ('student_fatheredu', models.CharField(default='', max_length=50)),
                ('student_fatherattainment', models.CharField(default='', max_length=50)),
                ('student_parentaddress', models.CharField(default='', max_length=50)),
                ('student_statusofreg', models.CharField(default='', max_length=20)),
                ('student_returnlastattended', models.CharField(default='', max_length=20)),
                ('student_shiftfrom', models.CharField(default='', max_length=50)),
                ('student_shiftto', models.CharField(default='', max_length=50)),
                ('student_transferfrom', models.CharField(default='', max_length=50)),
                ('student_entrancescore', models.CharField(default='', max_length=10)),
                ('student_credentials', models.CharField(default='', max_length=50)),
                ('student_scholarshipprivilege', models.CharField(default='', max_length=50)),
                ('student_campus', models.CharField(default='', max_length=30)),
                ('student_father_income', models.CharField(default='', max_length=30)),
                ('student_mother_income', models.CharField(default='', max_length=30)),
                ('student_emergency_contactname', models.CharField(default='', max_length=50)),
                ('student_emergency_contactnumber', models.CharField(default='', max_length=50)),
                ('student_emergency_contactaddress', models.CharField(default='', max_length=50)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.course')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.session')),
                ('year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.yearlevel')),
            ],
            options={
                'indexes': [models.Index(fields=['student_campus'], name='user_studen_student_cb826d_idx')],
            },
        ),
    ]
